export const categories = [
    {
        id: 1,
        name: 'Pizza',
        image: require('../assets/images/pizzaIcon.png'), 
    },
    {
        id: 2,
        name: 'Burger',
        image: require('../assets/images/burgerIcon.png'), 
    },
    {
        id: 3,
        name: 'Italian',
        image: require('../assets/images/italianIcon.png'), 
    },
    {
        id: 4,
        name: 'Chinese',
        image: require('../assets/images/chineseIcon.png'), // Updated with a unique image
    },
    {
        id: 5,
        name: 'Noodles',
        image: require('../assets/images/noodlesIcon.png'), // Updated with a unique image
    },
    {
        id: 6,
        name: 'Sweets',
        image: require('../assets/images/pizzaIcon.png'), // Updated with a unique image
    },
    
];
export const featured = [
    {
      id: 1,
      name: 'Papa Johns Pizza',
      restaurant: [
          {
              id: 1,
              name: 'Dilshan',
          },
      ],
      image: require('../assets/images/pizzaIcon.png'),
      description: 'Hot and spicy pizzas',
      lng: 80.953326,
      lat:7.356993,
      address: '434 Second Street',
      stars: 4,
      reviews: '4.4k',
      category: 'Fast Food',
        
        dishes: [
            {
                id: 1,
                name: 'Papa Johns pizza aaa',
                description: 'Cheesy garlic pizza',
                price: 10,
                lng: 80.953326,
                lat:7.356993,
                
                stars: 4,
                reviews: 4,
                image: require('../assets/images/1.jpg'),
                category: 'Italian',
                location: 'Beachside, Hambantota',
                
                dishes: [
                  {
                    id: 1,
                    name: 'Papa Johns pizza',
                    description: 'Cheesy garlic pizza',
                    price: 10,
                    
                    
                    stars: 4,
                    reviews: 4,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'Beachside, Hambantota',
                  },
                  {
                    id: 2,
                    name: 'Spaghetti Bolognese',
                    description: 'Classic Italian pasta with meat sauce',
                    price: 12,
                    stars: 5,
                    
                    reviews: 10,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'City Center, Colombo',
                  },
                  {
                    id: 3,
                    name: 'Chicken Biriyani',
                    description: 'Flavorful spiced rice with tender chicken',
                    price: 8,
                    stars: 4.5,
                  
                    reviews: 15,
                    image: require('../assets/images/1.jpg'),
                    category: 'Indian',
                    location: 'Main Street, Galle',
                  },
                  {
                    id: 4,
                    name: 'Beef Burger',
                    description: 'Juicy beef patty with fresh lettuce and tomato',
                    price: 7,
                    stars: 4.3,
                    reviews: 8,
                    image: require('../assets/images/1.jpg'),
                    category: 'Fast Food',
                    location: 'Seaview, Negombo',
                  },
                  {
                    id: 5,
                    name: 'Sushi Platter',
                    description: 'Assorted sushi rolls with fresh fish and vegetables',
                    price: 200,
                    stars: 4.8,
                    reviews: 25,
                    image: require('../assets/images/1.jpg'),
                    category: 'Japanese',
                    location: 'Riverside, Kandy',
                  },
                  {
                    id: 6,
                    name: 'Sushi Platter',
                    description: 'Assorted sushi rolls with fresh fish and vegetables',
                    price: 200,
                    stars: 4.8,
                    reviews: 25,
                    image: require('../assets/images/1.jpg'),
                    category: 'Japanese',
                    location: 'Riverside, Kandy',
                  },
                  
                ],
              },
                          
              {
                id: 2,
                name: 'Pizza',
                description: 'Cheesy garlic pizza',
                restaurant: [
                  {
                      id: 1,
                      name1: 'Dilshan d',
                  },
              ],
                lng: 80.953326,
                lat:7.356993,
                price: 10,
                stars: 4.8,
                reviews: 4.8,
                image: require('../assets/images/1.jpg'),
                category: 'Italian',
                location: 'Ella, Sri Lanka',
                dishes: [
                  {
                    id: 1,
                    name: 'Papa Johns pizza',
                    description: 'Cheesy garlic pizza',
                    price: 100,
                    stars: 4,
                    reviews: 4,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'Beachside, Hambantota',
                  },
                  {
                    id: 2,
                    name: 'Spaghetti Bolognese',
                    description: 'Classic Italian pasta with meat sauce',
                    price: 12,
                    stars: 5,
                    reviews: 10,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'City Center, Colombo',
                  },
                  {
                    id: 3,
                    name: 'Chicken Biriyani',
                    description: 'Flavorful spiced rice with tender chicken',
                    price: 8,
                    stars: 4.5,
                    reviews: 15,
                    image: require('../assets/images/1.jpg'),
                    category: 'Indian',
                    location: 'Main Street, Galle',
                  },
                  {
                    id: 4,
                    name: 'Beef Burger',
                    description: 'Juicy beef patty with fresh lettuce and tomato',
                    price: 7,
                    stars: 4.3,
                    reviews: 8,
                    image: require('../assets/images/1.jpg'),
                    category: 'Fast Food',
                    location: 'Seaview, Negombo',
                  },
                  {
                    id: 5,
                    name: 'Sushi Platter',
                    description: 'Assorted sushi rolls with fresh fish and vegetables',
                    price: 20,
                    stars: 4.8,
                    reviews: 25,
                    image: require('../assets/images/1.jpg'),
                    category: 'Japanese',
                    location: 'Riverside, Kandy',
                  },
                 
                ],
              }
        ],
    },
    {
        id: 2,
        name: 'Pepperoni  Pizza  ',
        image: require('../assets/images/burgerIcon.png'),
        description: 'Home of the Whopper',
        lng: 80.953326,
        lat:7.356993,
        address: '123 Broadway',
        stars: 5,
        reviews: '3.8k',
        category: 'Fast Food',
        dishes: [
            {
                id: 1,
                name: 'Pepperoni Pizza',
                description: 'Cheesy pizza topped with spicy pepperoni slices',
                price: 18,
                stars: 4.9,
                lng: 80.953326,
                lat:7.356993,
                reviews: 150,
                image: require('../assets/images/1.jpg'),
                category: 'Pizza',
                location: 'Kandy, Sri Lanka',
                dishes: [
                  {
                    id: 1,
                    name: 'Papa Johns pizza',
                    description: 'Cheesy garlic pizza',
                    price: 10,
                    stars: 4,
                    reviews: 4,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'Beachside, Hambantota',
                  },
                  {
                    id: 2,
                    name: 'Spaghetti Bolognese',
                    description: 'Classic Italian pasta with meat sauce',
                    price: 12,
                    stars: 5,
                    reviews: 10,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'City Center, Colombo',
                  },
                  {
                    id: 3,
                    name: 'Chicken Biriyani',
                    description: 'Flavorful spiced rice with tender chicken',
                    price: 8,
                    stars: 4.5,
                    reviews: 15,
                    image: require('../assets/images/1.jpg'),
                    category: 'Indian',
                    location: 'Main Street, Galle',
                  },
                  {
                    id: 4,
                    name: 'Beef Burger',
                    description: 'Juicy beef patty with fresh lettuce and tomato',
                    price: 7,
                    stars: 4.3,
                    reviews: 8,
                    image: require('../assets/images/1.jpg'),
                    category: 'Fast Food',
                    location: 'Seaview, Negombo',
                  },
                  {
                    id: 5,
                    name: 'Sushi Platter',
                    description: 'Assorted sushi rolls with fresh fish and vegetables',
                    price: 20,
                    stars: 4.8,
                    reviews: 25,
                    image: require('../assets/images/1.jpg'),
                    category: 'Japanese',
                    location: 'Riverside, Kandy',
                  },
                  
                ],
              },
              {
                id: 2,
                name: 'Margherita Pizza',
                description: 'Classic Italian pizza with fresh tomatoes, mozzarella, and basil',
                price: 15,
                stars: 4.8,
                lng: 80.953326,
                lat:7.356993,
                reviews: 120,
                image: require('../assets/images/1.jpg'),
                category: 'Pizza',
                location: 'Negombo, Sri Lanka',
                dishes: [
                  {
                    id: 1,
                    name: 'Papa Johns pizza',
                    description: 'Cheesy garlic pizza',
                    price: 10,
                    stars: 4,
                    reviews: 4,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'Beachside, Hambantota',
                  },
                  {
                    id: 2,
                    name: 'Spaghetti Bolognese',
                    description: 'Classic Italian pasta with meat sauce',
                    price: 12,
                    stars: 5,
                    reviews: 10,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'City Center, Colombo',
                  },
                  {
                    id: 3,
                    name: 'Chicken Biriyani',
                    description: 'Flavorful spiced rice with tender chicken',
                    price: 8,
                    stars: 4.5,
                    reviews: 15,
                    image: require('../assets/images/1.jpg'),
                    category: 'Indian',
                    location: 'Main Street, Galle',
                  },
                  {
                    id: 4,
                    name: 'Beef Burger',
                    description: 'Juicy beef patty with fresh lettuce and tomato',
                    price: 7,
                    stars: 4.3,
                    reviews: 8,
                    image: require('../assets/images/1.jpg'),
                    category: 'Fast Food',
                    location: 'Seaview, Negombo',
                  },
                  {
                    id: 5,
                    name: 'Sushi Platter',
                    description: 'Assorted sushi rolls with fresh fish and vegetables',
                    price: 20,
                    stars: 4.8,
                    reviews: 25,
                    image: require('../assets/images/1.jpg'),
                    category: 'Japanese',
                    location: 'Riverside, Kandy',
                  },
                  
                ],
              }
        ],
    },
    {
        id: 3,
        name: 'Veggie Pizza',
        image: require('../assets/images/burgerIcon.png'),
        description: 'The ultimate destination for burger lovers',
        lng: 34.052235,
        lat: -118.243683,
        address: '456 Sunset Boulevard, Los Angeles',
        stars: 4.8,
        reviews: '5.2k',
        category: 'Fast Food',
        dishes: [
            {
                id: 1,
                name: 'Veggie Supreme Pizza',
                description: 'Loaded with bell peppers, onions, olives, and mushrooms',
                price: 16,
                stars: 4.7,
                lng: 80.953326,
                lat:7.356993,
                reviews: 100,
                image: require('../assets/images/1.jpg'),
                category: 'Pizza',
                location: 'Colombo, Sri Lanka',  
                dishes: [
                  {
                    id: 1,
                    name: 'Papa Johns pizza',
                    description: 'Cheesy garlic pizza',
                    price: 10,
                    stars: 4,
                    reviews: 4,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'Beachside, Hambantota',
                  },
                  {
                    id: 2,
                    name: 'Spaghetti Bolognese',
                    description: 'Classic Italian pasta with meat sauce',
                    price: 12,
                    stars: 5,
                    reviews: 10,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'City Center, Colombo',
                  },
                  {
                    id: 3,
                    name: 'Chicken Biriyani',
                    description: 'Flavorful spiced rice with tender chicken',
                    price: 8,
                    stars: 4.5,
                    reviews: 15,
                    image: require('../assets/images/1.jpg'),
                    category: 'Indian',
                    location: 'Main Street, Galle',
                  },
                  {
                    id: 4,
                    name: 'Beef Burger',
                    description: 'Juicy beef patty with fresh lettuce and tomato',
                    price: 7,
                    stars: 4.3,
                    reviews: 8,
                    image: require('../assets/images/1.jpg'),
                    category: 'Fast Food',
                    location: 'Seaview, Negombo',
                  },
                  {
                    id: 5,
                    name: 'Sushi Platter',
                    description: 'Assorted sushi rolls with fresh fish and vegetables',
                    price: 20,
                    stars: 4.8,
                    reviews: 25,
                    image: require('../assets/images/1.jpg'),
                    category: 'Japanese',
                    location: 'Riverside, Kandy',
                  },
                  
                ],
                
                  
                  },
              {
                id: 2,
                name: 'BBQ Chicken Pizza',
                description: 'Grilled chicken with tangy BBQ sauce and melted cheese',
                price: 20,
                stars: 4.6,
                reviews: 110,
                lng: 80.953326,
                lat:7.356993,
                category: 'Pizza',
                location: 'Galle, Sri Lanka',
                image: require('../assets/images/1.jpg'),
                dishes: [
                  {
                    id: 1,
                    name: 'Papa Johns pizza',
                    description: 'Cheesy garlic pizza',
                    price: 10,
                    stars: 4,
                    reviews: 4,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'Beachside, Hambantota',
                  },
                  {
                    id: 2,
                    name: 'Spaghetti Bolognese',
                    description: 'Classic Italian pasta with meat sauce',
                    price: 12,
                    stars: 5,
                    reviews: 10,
                    image: require('../assets/images/1.jpg'),
                    category: 'Italian',
                    location: 'City Center, Colombo',
                  },
                  {
                    id: 3,
                    name: 'Chicken Biriyani',
                    description: 'Flavorful spiced rice with tender chicken',
                    price: 8,
                    stars: 4.5,
                    reviews: 15,
                    image: require('../assets/images/1.jpg'),
                    category: 'Indian',
                    location: 'Main Street, Galle',
                  },
                  {
                    id: 4,
                    name: 'Beef Burger',
                    description: 'Juicy beef patty with fresh lettuce and tomato',
                    price: 7,
                    stars: 4.3,
                    reviews: 8,
                    image: require('../assets/images/1.jpg'),
                    category: 'Fast Food',
                    location: 'Seaview, Negombo',
                  },
                  {
                    id: 5,
                    name: 'Sushi Platter',
                    description: 'Assorted sushi rolls with fresh fish and vegetables',
                    price: 20,
                    stars: 4.8,
                    reviews: 25,
                    image: require('../assets/images/1.jpg'),
                    category: 'Japanese',
                    location: 'Riverside, Kandy',
                  },
                  
                ],
              }
            
        ],
    }
    
];
